### ISSUE TITLE
Debian compatibility

### ISSUE THREAD

**Issue by mahdi-ln** [Intika-Linux-Firewall/Iptables-Editor-Gui#1]
```
$ sudo ./ipteditor
Traceback (most recent call last):
	2: from ./ipteditor:18:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- gettext (LoadError)
```
Help please

**Comment by intika** [comment]
You are probably missing `ruby-gettext` package... install the listed packages bellow (i may update the readme)

```
ruby-rdoc
ruby-atk
ruby
ruby-cairo
ruby-json
ruby-glib2
ruby-gettext
ruby-gtk2-devel
ruby-locale
ruby-irb
ruby-pango
ruby-text
ruby-RubyGems
ruby-pkg-config
ruby-gtk2
ruby-gdk_pixbuf2
```
This is an exhaustive list 

Let me know if you still have an error

**Comment by mahdi-ln** [comment]
Some how yes, now the error is
```
$  sudo ./ipteditor
/home/m/Downloads/Iptables-Editor-Gui/ipteditor-modules/ruleslist.rb:77:in `block in addCols': 'Pango::WRAP_WORD_CHAR' has been deprecated. Use 'Pango::WrapMode::WORD_CHAR' or ':word_char'.
Traceback (most recent call last):
	7: from ./ipteditor:344:in `<main>'
	6: from ./ipteditor:310:in `exec'
	5: from ./ipteditor:304:in `iptables'
	4: from /home/m/Downloads/Iptables-Editor-Gui/ipteditor-modules/tablesnotebook.rb:93:in `text='
	3: from /home/m/Downloads/Iptables-Editor-Gui/ipteditor-modules/tablesnotebook.rb:157:in `loadRules'
	2: from /home/m/Downloads/Iptables-Editor-Gui/ipteditor-modules/tablesnotebook.rb:157:in `each'
	1: from /home/m/Downloads/Iptables-Editor-Gui/ipteditor-modules/tablesnotebook.rb:179:in `block in loadRules'
/home/m/Downloads/Iptables-Editor-Gui/ipteditor-modules/chainsnotebook.rb:61:in `addChain': undefined method `policy=' for nil:NilClass (NoMethodError)
```
on Ubuntu 18, I used below names:
```
sudo apt install ruby-cairo ruby ruby-cairo rdoc ruby-json ruby-glib2 ruby-gettext ruby-gtk2  ruby-locale irb ruby-pango ruby-text rubygems ruby-pkg-config ruby-gdk-pixbuf2 ```

**Comment by intika** [comment]
i am looking for a solution i'll post back an other answer... is the gui displayed if you run it without sudo or do you have the same error ?

**Comment by intika** [comment]
This is either caused by difference in debian based system (i am using a RHEL based system) or newer version of ruby... any way i guess the code needs to be updated to work with ubuntu i'll look into that and update the code when i have the time i added this to the "work in progress/todo" https://github.com/Intika-Linux-Firewall/Iptables-Editor-Gui/issues/2 i'll ping you here ;)
