### ISSUE TITLE
in centos7.3,cannot run

### ISSUE THREAD

**Issue by xinpengliu** [Intika-Linux-Firewall/Iptables-Editor-Gui#3]
[root@node3 Iptables-Editor-Gui]# ./ipteditor
Traceback (most recent call last):
        7: from ./ipteditor:344:in `<main>'
        6: from ./ipteditor:310:in `exec'
        5: from ./ipteditor:304:in `iptables'
        4: from /root/Iptables-Editor-Gui/ipteditor-modules/tablesnotebook.rb:93:in `text='
        3: from /root/Iptables-Editor-Gui/ipteditor-modules/tablesnotebook.rb:157:in `loadRules'
        2: from /root/Iptables-Editor-Gui/ipteditor-modules/tablesnotebook.rb:157:in `each'
        1: from /root/Iptables-Editor-Gui/ipteditor-modules/tablesnotebook.rb:179:in `block in loadRules'
/root/Iptables-Editor-Gui/ipteditor-modules/chainsnotebook.rb:61:in `addChain': undefined method `policy=' for nil:NilClass (NoMethodError)

**Comment by jagiella** [comment]
Same problem on Ubuntu 18.04.

I installed the following dependencies:
```
sudo apt install ruby
sudo apt install ruby-gtk2
sudo gem install gettext
```

**Comment by amiltonjr** [comment]
On CentOS 7 I am having the following issue:

```
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- gettext (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./ipteditor:18:in `<main>
```

**Comment by mclaudt** [comment]
Same on Ubuntu 20.04 LTS

**Comment by mclaudt** [comment]
> On CentOS 7 I am having the following issue:
> 
> ```
> /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- gettext (LoadError)
> 	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from ./ipteditor:18:in `<main>
> ```

Your issue is due to the lack of gettext. Just do `sudo gem install gettext`.
