### ISSUE TITLE
Trouble running the app

### ISSUE THREAD

**Issue by teicors** [Intika-Linux-Firewall/Iptables-Editor-Gui#5]
Hi,
I followed the direction  to sole the issue 
...  cannot load such file -- gettext (LoadError)
but now  I'm facing another issue:
Gtk-Message: 15:54:26.636: Failed to load module "canberra-gtk-module"
/home/angelo/Iptables-Editor-Gui/ipteditor-modules/ruleslist.rb:77:in `block in addCols': 'Pango::WRAP_WORD_CHAR' has been deprecated. Use 'Pango::WrapMode::WORD_CHAR' or ':word_char'.
Traceback (most recent call last):
	7: from ./ipteditor:344:in `<main>'
	6: from ./ipteditor:310:in `exec'
	5: from ./ipteditor:304:in `iptables'
	4: from /home/angelo/Iptables-Editor-Gui/ipteditor-modules/tablesnotebook.rb:93:in `text='
	3: from /home/angelo/Iptables-Editor-Gui/ipteditor-modules/tablesnotebook.rb:157:in `loadRules'
	2: from /home/angelo/Iptables-Editor-Gui/ipteditor-modules/tablesnotebook.rb:157:in `each'
	1: from /home/angelo/Iptables-Editor-Gui/ipteditor-modules/tablesnotebook.rb:179:in `block in loadRules'
/home/angelo/Iptables-Editor-Gui/ipteditor-modules/chainsnotebook.rb:61:in `addChain': undefined method `policy=' for nil:NilClass (NoMethodError)

**Comment by teicors** [comment]
I changed into the file ipteditor-modules/iptenotebook.rb the line 86 from 
`when 'Fixnum' `
to 
`when 'Integer'`
and I can run the soft, but double clicking on the line let the app crash with this error:
```
Iptables-Editor-Gui/ipteditor-modules/ruleslist.rb:147:in `editaCelula': undefined method `name' for #<Gtk::TreeViewColumn:0x2e35574 ptr=0x2fda848>
	 from /home/angelo/Iptables-Editor-Gui/ipteditor-modules/ruleslist.rb:30:in `block in initialize'
	 from ./ipteditor:312:in `main'
	 from ./ipteditor:312:in `exec'
	 from ./ipteditor:344:in `<main>'

```
