### ISSUE TITLE
Traceback Error on Start

### ISSUE THREAD

**Issue by DadTheTester** [Intika-Linux-Firewall/Iptables-Editor-Gui#6]
Running on Debian 10
sudo ./ipteditor

Traceback (most recent call last):
        2: from ./ipteditor:18:in `<main>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- gettext (LoadError)

**Comment by ZitroWasTaken** [comment]
Same thing on Arch

**Comment by lightydo** [comment]
sudo gem install gettext
